Name: 1.Healer_Human
Species: 1
Parts:
- Name: SK_HUMN_BASE_01_01HEAD_HU01
  PartType: Head
  PartVersion: 1
- Name: SK_HUMN_BASE_07_02HAIR_HU01
  PartType: Hair
  PartVersion: 1
- Name: SK_HUMN_BASE_06_03EBRL_HU01
  PartType: EyebrowLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_06_04EBRR_HU01
  PartType: EyebrowRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_05EYEL_HU01
  PartType: EyeLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_06EYER_HU01
  PartType: EyeRight
  PartVersion: 1
- Name: SK_HUMN_BASE_04_07EARL_HU01
  PartType: EarLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_02_08EARR_HU01
  PartType: EarRight
  PartVersion: 1
- Name: SK_HUMN_BASE_06_35NOSE_HU01
  PartType: Nose
  PartVersion: 1
- Name: SK_HUMN_BASE_10_36TETH_HU01
  PartType: Teeth
  PartVersion: 1
- Name: SK_HUMN_BASE_01_37TONG_HU01
  PartType: Tongue
  PartVersion: 1
- Name: SK_FANT_KNGT_17_11AUPL_HU01
  PartType: ArmUpperLeft
  PartVersion: 1
- Name: SK_FANT_KNGT_17_12AUPR_HU01
  PartType: ArmUpperRight
  PartVersion: 1
- Name: SK_FANT_KNGT_17_25AHPF_HU01
  PartType: AttachmentHipsFront
  PartVersion: 1
- Name: SK_FANT_KNGT_17_13ALWL_HU01
  PartType: ArmLowerLeft
  PartVersion: 1
- Name: SK_FANT_KNGT_17_10TORS_HU01
  PartType: Torso
  PartVersion: 1
- Name: SK_FANT_KNGT_17_15HNDL_HU01
  PartType: HandLeft
  PartVersion: 1
- Name: SK_FANT_KNGT_17_21FOTR_HU01
  PartType: FootRight
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_22AHED_HU01
  PartType: AttachmentHead
  PartVersion: 1
- Name: SK_FANT_KNGT_17_28AHPR_HU01
  PartType: AttachmentHipsRight
  PartVersion: 1
- Name: SK_HUMN_BASE_06_09FCHR_HU01
  PartType: FacialHair
  PartVersion: 1
- Name: SK_FANT_KNGT_17_14ALWR_HU01
  PartType: ArmLowerRight
  PartVersion: 1
- Name: SK_FANT_KNGT_17_16HNDR_HU01
  PartType: HandRight
  PartVersion: 1
- Name: SK_FANT_KNGT_17_33AKNL_HU01
  PartType: AttachmentKneeLeft
  PartVersion: 1
- Name: SK_FANT_KNGT_17_20FOTL_HU01
  PartType: FootLeft
  PartVersion: 1
- Name: SK_FANT_KNGT_17_19LEGR_HU01
  PartType: LegRight
  PartVersion: 1
- Name: SK_FANT_KNGT_17_18LEGL_HU01
  PartType: LegLeft
  PartVersion: 1
- Name: SK_FANT_KNGT_17_26AHPB_HU01
  PartType: AttachmentHipsBack
  PartVersion: 1
- Name: SK_FANT_KNGT_17_31AEBL_HU01
  PartType: AttachmentElbowLeft
  PartVersion: 1
- Name: SK_FANT_KNGT_17_34AKNR_HU01
  PartType: AttachmentKneeRight
  PartVersion: 1
- Name: SK_FANT_KNGT_17_27AHPL_HU01
  PartType: AttachmentHipsLeft
  PartVersion: 1
- Name: SK_FANT_KNGT_17_17HIPS_HU01
  PartType: Hips
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_23AFAC_HU01
  PartType: AttachmentFace
  PartVersion: 1
- Name: SK_FANT_KNGT_17_32AEBR_HU01
  PartType: AttachmentElbowRight
  PartVersion: 1
ColorSet:
  Species: 1
  Name: Custom
  SourceColorPath: Assets\Prefabs\2.Dealer_Human\Textures\T_2.Dealer_HumanColorMap.png
  SourceMetallicPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_MetallicMap.png
  SourceSmoothnessPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_SmoothnessMap.png
  SourceReflectionPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_ReflectionMap.png
  SourceEmissionPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_EmissionMap.png
  SourceOpacityPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_OpacityMap.png
ColorRows:
- ColorProperty: 1
  MainColor: EAB38B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 2
  MainColor: EAB38B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 3
  MainColor: EAB38B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 4
  MainColor: D09A78
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 5
  MainColor: EAB38B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 6
  MainColor: EAB38B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 7
  MainColor: EAB38B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 8
  MainColor: CD9C7D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 9
  MainColor: CD9C7D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 10
  MainColor: CD9C7D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 11
  MainColor: CD9C7D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 12
  MainColor: CD9C7D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 13
  MainColor: CD9C7D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 14
  MainColor: EAB38B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 15
  MainColor: E79A9C
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 16
  MainColor: FFF3CE
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 17
  MainColor: E5D8AF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 18
  MainColor: E79A9C
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 19
  MainColor: E79A9C
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 20
  MainColor: D0D0D0
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 21
  MainColor: D0D0D0
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 22
  MainColor: 6B4A27
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 23
  MainColor: 6B4A27
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 24
  MainColor: 262626
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 25
  MainColor: 262626
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 26
  MainColor: 8F6B46
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 27
  MainColor: 8F6B46
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 28
  MainColor: FFFFFF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 29
  MainColor: FFFFFF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 30
  MainColor: 6F5744
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 31
  MainColor: 6F5744
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 32
  MainColor: 6F5744
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 33
  MainColor: 6F5744
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 34
  MainColor: CAA58E
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 35
  MainColor: 6F5744
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 36
  MainColor: 6F5744
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 37
  MainColor: CAA58E
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 38
  MainColor: B35149
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 39
  MainColor: 944842
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 40
  MainColor: AFA382
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 41
  MainColor: 94896F
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 42
  MainColor: 785B4A
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 43
  MainColor: BD9337
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 44
  MainColor: AFAA92
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 45
  MainColor: 43413D
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 46
  MainColor: 62594F
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 47
  MainColor: 785B4A
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 48
  MainColor: 785B4A
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 49
  MainColor: BD9337
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 50
  MainColor: AFAA92
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 51
  MainColor: 43708A
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 52
  MainColor: 785B4A
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 53
  MainColor: 785B4A
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 54
  MainColor: BD9337
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 55
  MainColor: AFAA92
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 56
  MainColor: 43708A
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 57
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 58
  MainColor: 9D8E6B
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 59
  MainColor: BD9337
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 60
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 61
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 62
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 63
  MainColor: 9D8E6B
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 64
  MainColor: BD9337
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 65
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 66
  MainColor: 383838
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 67
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 68
  MainColor: 2B2B2B
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 69
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 70
  MainColor: 3F4053
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 71
  MainColor: 3F4053
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 72
  MainColor: 3F4053
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 73
  MainColor: 6F5C3C
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 74
  MainColor: 908063
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 75
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 76
  MainColor: 524331
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 77
  MainColor: 3F4053
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 78
  MainColor: 6F5C3C
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 79
  MainColor: 908063
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 80
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 81
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 82
  MainColor: 6F5C3C
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 83
  MainColor: 6F5C3C
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 84
  MainColor: 423525
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 85
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 86
  MainColor: 383838
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 87
  MainColor: 6F5C3C
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 88
  MainColor: 6F5C3C
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 89
  MainColor: 423525
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 90
  MainColor: 383838
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 91
  MainColor: 383838
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 92
  MainColor: AF8D44
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 93
  MainColor: 5172A5
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 94
  MainColor: 848484
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 95
  MainColor: 4C3A2D
  Metallic: B7B7B7
  Smoothness: B7B7B7
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 96
  MainColor: 282E3C
  Metallic: B7B7B7
  Smoothness: B7B7B7
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 97
  MainColor: 222221
  Metallic: B7B7B7
  Smoothness: B7B7B7
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 98
  MainColor: 72695E
  Metallic: B7B7B7
  Smoothness: B7B7B7
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 99
  MainColor: 2A2D31
  Metallic: B7B7B7
  Smoothness: B7B7B7
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 100
  MainColor: 4C3A2D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 101
  MainColor: 2D364C
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 102
  MainColor: 2A2928
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 103
  MainColor: 8D806F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 104
  MainColor: 32363D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 105
  MainColor: 4C3A2D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 106
  MainColor: 2D364C
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 107
  MainColor: 2A2928
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 108
  MainColor: 8D806F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 109
  MainColor: 32363D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 110
  MainColor: 4C3A2D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 111
  MainColor: 604E35
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 112
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 113
  MainColor: 898580
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 114
  MainColor: 76726C
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 115
  MainColor: 4C3A2D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 116
  MainColor: 604E35
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 117
  MainColor: 504B45
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 118
  MainColor: 7D7973
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 119
  MainColor: 6A6660
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 120
  MainColor: 4C3A2D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 121
  MainColor: 604E35
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 122
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 123
  MainColor: 898580
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 124
  MainColor: 76726C
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 125
  MainColor: 4C3A2D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 126
  MainColor: 604E35
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 127
  MainColor: 504B45
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 128
  MainColor: 7D7973
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 129
  MainColor: 6A6660
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 130
  MainColor: 4C3A2D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 131
  MainColor: 604E35
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 132
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 133
  MainColor: 898580
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 134
  MainColor: 76726C
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 135
  MainColor: 4C3A2D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 136
  MainColor: 604E35
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 137
  MainColor: 504B45
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 138
  MainColor: 7D7973
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 139
  MainColor: 6A6660
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 140
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 141
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 142
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 143
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 144
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 145
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 146
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 147
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 148
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 149
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 150
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 151
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 152
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 153
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 154
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 155
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 156
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 157
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 158
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 159
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 160
  MainColor: 717171
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 161
  MainColor: 656864
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 162
  MainColor: 555754
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 163
  MainColor: 454646
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 164
  MainColor: A1ABC5
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 165
  MainColor: 8196BE
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 166
  MainColor: F7F07F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 167
  MainColor: F9D92A
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 168
  MainColor: 769DDF
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: 000000
- ColorProperty: 169
  MainColor: 6C81B9
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: 000000
- ColorProperty: 170
  MainColor: F9D92A
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 171
  MainColor: 91F92A
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 172
  MainColor: 9A9FA2
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 173
  MainColor: 949AA2
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 174
  MainColor: 8D997D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 175
  MainColor: 838865
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 176
  MainColor: 33312E
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 177
  MainColor: 282623
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 178
  MainColor: 74726B
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 179
  MainColor: 887969
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 180
  MainColor: 746251
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 181
  MainColor: 746251
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 182
  MainColor: 614F43
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 183
  MainColor: 4E3E33
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 184
  MainColor: 44392E
  Metallic: AAAAAA
  Smoothness: AAAAAA
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 185
  MainColor: 503F31
  Metallic: AAAAAA
  Smoothness: AAAAAA
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 186
  MainColor: 3E3228
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 187
  MainColor: 685647
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 188
  MainColor: B19675
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 189
  MainColor: 796B59
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 190
  MainColor: 645C51
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 191
  MainColor: 534B41
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 192
  MainColor: BDB7B1
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 193
  MainColor: AAA5A0
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 194
  MainColor: 3D332F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 195
  MainColor: 564941
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 196
  MainColor: 945F42
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 197
  MainColor: 6D5344
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 198
  MainColor: 7B7879
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 199
  MainColor: 565656
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
BlendShapes:
  BodyTypeValue: 100
  BodySizeValue: -60
  MuscleValue: -100
