Name: 2.Tank_Human
Species: 1
Parts:
- Name: SK_HUMN_BASE_01_01HEAD_HU01
  PartType: Head
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_29ASHL_HU01
  PartType: AttachmentShoulderLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_03EBRL_HU01
  PartType: EyebrowLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_04EBRR_HU01
  PartType: EyebrowRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_05EYEL_HU01
  PartType: EyeLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_06EYER_HU01
  PartType: EyeRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_07EARL_HU01
  PartType: EarLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_08EARR_HU01
  PartType: EarRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_35NOSE_HU01
  PartType: Nose
  PartVersion: 1
- Name: SK_HUMN_BASE_01_36TETH_HU01
  PartType: Teeth
  PartVersion: 1
- Name: SK_HUMN_BASE_01_37TONG_HU01
  PartType: Tongue
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_11AUPL_HU01
  PartType: ArmUpperLeft
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_12AUPR_HU01
  PartType: ArmUpperRight
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_25AHPF_HU01
  PartType: AttachmentHipsFront
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_13ALWL_HU01
  PartType: ArmLowerLeft
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_10TORS_HU01
  PartType: Torso
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_15HNDL_HU01
  PartType: HandLeft
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_21FOTR_HU01
  PartType: FootRight
  PartVersion: 1
- Name: SK_FANT_KNGT_17_22AHED_HU01
  PartType: AttachmentHead
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_28AHPR_HU01
  PartType: AttachmentHipsRight
  PartVersion: 1
- Name: SK_HUMN_BASE_08_09FCHR_HU01
  PartType: FacialHair
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_14ALWR_HU01
  PartType: ArmLowerRight
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_16HNDR_HU01
  PartType: HandRight
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_33AKNL_HU01
  PartType: AttachmentKneeLeft
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_20FOTL_HU01
  PartType: FootLeft
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_19LEGR_HU01
  PartType: LegRight
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_18LEGL_HU01
  PartType: LegLeft
  PartVersion: 1
- Name: SK_SCFI_CIVL_10_26AHPB_HU01
  PartType: AttachmentHipsBack
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_34AKNR_HU01
  PartType: AttachmentKneeRight
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_27AHPL_HU01
  PartType: AttachmentHipsLeft
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_17HIPS_HU01
  PartType: Hips
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_30ASHR_HU01
  PartType: AttachmentShoulderRight
  PartVersion: 1
ColorSet:
  Species: 1
  Name: Custom
  SourceColorPath: Assets\Prefabs\1.Healer_Human\Textures\T_1.Healer_HumanColorMap.png
  SourceMetallicPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_MetallicMap.png
  SourceSmoothnessPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_SmoothnessMap.png
  SourceReflectionPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_ReflectionMap.png
  SourceEmissionPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_EmissionMap.png
  SourceOpacityPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_OpacityMap.png
ColorRows:
- ColorProperty: 1
  MainColor: FCC19C
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 2
  MainColor: FCC19C
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 3
  MainColor: FCC19C
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 4
  MainColor: DAA07F
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 5
  MainColor: FCC19C
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 6
  MainColor: F8C5A5
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 7
  MainColor: FCC19C
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 8
  MainColor: D9A78B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 9
  MainColor: D9A78B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 10
  MainColor: D9A78B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 11
  MainColor: D9A78B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 12
  MainColor: D9A78B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 13
  MainColor: D9A78B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 14
  MainColor: FCC19C
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 15
  MainColor: E79A9C
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 16
  MainColor: FFF3CE
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 17
  MainColor: E5D8AF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 18
  MainColor: E79A9C
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 19
  MainColor: E79A9C
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 20
  MainColor: D0D0D0
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 21
  MainColor: D0D0D0
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 22
  MainColor: 5D7095
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 23
  MainColor: 5D7095
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 24
  MainColor: 262626
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 25
  MainColor: 262626
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 26
  MainColor: 607DB7
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 27
  MainColor: 607DB7
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 28
  MainColor: FFFFFF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 29
  MainColor: FFFFFF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 30
  MainColor: DAB884
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 31
  MainColor: DAB884
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 32
  MainColor: DAB884
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 33
  MainColor: DAB884
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 34
  MainColor: AA9B83
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 35
  MainColor: DAB884
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 36
  MainColor: DAB884
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 37
  MainColor: CAA58E
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 38
  MainColor: B35149
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 39
  MainColor: 944842
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 40
  MainColor: AFA382
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 41
  MainColor: 94896F
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 42
  MainColor: 806D4B
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 43
  MainColor: 515D3A
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 44
  MainColor: 4A4238
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 45
  MainColor: 7D6652
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 46
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 47
  MainColor: 806D4B
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 48
  MainColor: 515D3A
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 49
  MainColor: 4A4238
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 50
  MainColor: 7D6652
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 51
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 52
  MainColor: 806D4B
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 53
  MainColor: 515D3A
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 54
  MainColor: 4A4238
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 55
  MainColor: 7D6652
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 56
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 57
  MainColor: 806D4B
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 58
  MainColor: 515D3A
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 59
  MainColor: 4A4238
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 60
  MainColor: 7D6652
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 61
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 62
  MainColor: 806D4B
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 63
  MainColor: 515D3A
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 64
  MainColor: 4A4238
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 65
  MainColor: 7D6652
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 66
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 67
  MainColor: 433931
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 68
  MainColor: 515D3A
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 69
  MainColor: 473932
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 70
  MainColor: 6D5344
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 71
  MainColor: 6D5344
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 72
  MainColor: 433931
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 73
  MainColor: 7B6E53
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 74
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 75
  MainColor: 6D5344
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 76
  MainColor: 6D5344
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 77
  MainColor: 433931
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 78
  MainColor: 7B6E53
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 79
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 80
  MainColor: 6D5344
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 81
  MainColor: 6D5344
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 82
  MainColor: 69584A
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 83
  MainColor: 756033
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 84
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 85
  MainColor: 998B79
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 86
  MainColor: 575655
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 87
  MainColor: 69584A
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 88
  MainColor: 756033
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 89
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 90
  MainColor: 998B79
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 91
  MainColor: 575655
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 92
  MainColor: 7A593E
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 93
  MainColor: 7A593E
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 94
  MainColor: B7B7B7
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 95
  MainColor: 4C3A2D
  Metallic: B7B7B7
  Smoothness: B7B7B7
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 96
  MainColor: 282E3C
  Metallic: B7B7B7
  Smoothness: B7B7B7
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 97
  MainColor: 222221
  Metallic: B7B7B7
  Smoothness: B7B7B7
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 98
  MainColor: 72695E
  Metallic: B7B7B7
  Smoothness: B7B7B7
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 99
  MainColor: 2A2D31
  Metallic: B7B7B7
  Smoothness: B7B7B7
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 100
  MainColor: 4C3A2D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 101
  MainColor: 2D364C
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 102
  MainColor: 2A2928
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 103
  MainColor: 8D806F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 104
  MainColor: 32363D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 105
  MainColor: 4C3A2D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 106
  MainColor: 2D364C
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 107
  MainColor: 2A2928
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 108
  MainColor: 8D806F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 109
  MainColor: 32363D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 110
  MainColor: 7B5650
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 111
  MainColor: 998B79
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 112
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 113
  MainColor: 898580
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 114
  MainColor: 76726C
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 115
  MainColor: 76554E
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 116
  MainColor: 918473
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 117
  MainColor: 504B45
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 118
  MainColor: 7D7973
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 119
  MainColor: 6A6660
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 120
  MainColor: 7B5650
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 121
  MainColor: 998B79
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 122
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 123
  MainColor: 898580
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 124
  MainColor: 76726C
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 125
  MainColor: 76554E
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 126
  MainColor: 918473
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 127
  MainColor: 504B45
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 128
  MainColor: 7D7973
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 129
  MainColor: 6A6660
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 130
  MainColor: 7B5650
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 131
  MainColor: 998B79
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 132
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 133
  MainColor: 898580
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 134
  MainColor: 76726C
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 135
  MainColor: 76554E
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 136
  MainColor: 918473
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 137
  MainColor: 504B45
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 138
  MainColor: 7D7973
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 139
  MainColor: 6A6660
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 140
  MainColor: 7B5650
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 141
  MainColor: 998B79
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 142
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 143
  MainColor: 898580
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 144
  MainColor: 76726C
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 145
  MainColor: 76554E
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 146
  MainColor: 918473
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 147
  MainColor: 504B45
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 148
  MainColor: 7D7973
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 149
  MainColor: 6A6660
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 150
  MainColor: 7B5650
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 151
  MainColor: 998B79
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 152
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 153
  MainColor: 898580
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 154
  MainColor: 76726C
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 155
  MainColor: 76554E
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 156
  MainColor: 918473
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 157
  MainColor: 504B45
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 158
  MainColor: 7D7973
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 159
  MainColor: 6A6660
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 160
  MainColor: 7D736C
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 161
  MainColor: 6F685D
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 162
  MainColor: 5C564D
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 163
  MainColor: 49443F
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 164
  MainColor: C5A778
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 165
  MainColor: C99147
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 166
  MainColor: CD31A3
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 167
  MainColor: A32180
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 168
  MainColor: 90BAE4
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: 000000
- ColorProperty: 169
  MainColor: 88A6C4
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: 000000
- ColorProperty: 170
  MainColor: 0074FF
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 171
  MainColor: 00FFE4
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 172
  MainColor: 9A9FA2
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 173
  MainColor: 949AA2
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 174
  MainColor: 8D997D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 175
  MainColor: 838865
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 176
  MainColor: 373532
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 177
  MainColor: 2B2926
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 178
  MainColor: 6D6964
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 179
  MainColor: 4A4C52
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 180
  MainColor: 807663
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 181
  MainColor: 6C624E
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 182
  MainColor: 6C624E
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 183
  MainColor: 5B4E3F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 184
  MainColor: 5E4A39
  Metallic: AAAAAA
  Smoothness: AAAAAA
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 185
  MainColor: 524132
  Metallic: AAAAAA
  Smoothness: AAAAAA
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 186
  MainColor: 604A34
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 187
  MainColor: 4B3C2F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 188
  MainColor: 8D7557
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 189
  MainColor: 5B4F3E
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 190
  MainColor: 776B5B
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 191
  MainColor: 63584A
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 192
  MainColor: 97928D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 193
  MainColor: 86827E
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 194
  MainColor: 70563F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 195
  MainColor: 83684F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 196
  MainColor: 354798
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 197
  MainColor: 404870
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 198
  MainColor: 7B7879
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 199
  MainColor: 565656
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
BlendShapes:
  BodyTypeValue: -100
  BodySizeValue: 60
  MuscleValue: -10
